const A='images/';
const services=[
 {title:'Bridal Makeup',img:'highres/gallery-bridal-1.jpg',desc:'Complete bridal makeup for your special day.'},
 {title:'Hair Treatment',img:'highres/hero.jpg',desc:'Hair cutting, coloring, smoothing and more.'},
 {title:'Skin Care',img:'highres/skin.jpg',desc:'Facials, cleanups and skin treatments.'},
 {title:'Manicure & Pedicure',img:'highres/nails.jpg',desc:'Nail care for beautiful hands and feet.'},
 {title:'Body Massage',img:'highres/massage.jpg',desc:'Relaxing body massage to refresh your body.'},
 {title:'Mehndi Design',img:'highres/gallery-bridal-4.jpg',desc:'Beautiful celebration-ready artistry for every occasion.'}
];
const gallery=[
 {img:'highres/gallery-bridal-1.jpg',category:'bridal',alt:'Bridal beauty look'},
 {img:'highres/gallery-bridal-2.jpg',category:'bridal',alt:'Elegant bridal style'},
 {img:'highres/gallery-bridal-3.jpg',category:'bridal',alt:'Bridal fashion detail'},
 {img:'highres/gallery-bridal-4.jpg',category:'bridal',alt:'Celebration beauty look'},
 {img:'highres/gallery-makeup-1.jpg',category:'makeup',alt:'Professional makeup look'},
 {img:'highres/gallery-makeup-2.jpg',category:'makeup',alt:'Makeup and beauty portrait'},
 {img:'highres/hero.jpg',category:'hair',alt:'Healthy styled hair'},
 {img:'highres/gallery-hair-1.jpg',category:'hair',alt:'Hair styling inspiration'},
 {img:'highres/gallery-hair-2.jpg',category:'hair',alt:'Modern hair beauty portrait'},
 {img:'highres/mehndi.jpg',category:'mehndi',alt:'Hand beauty detail'},
 {img:'highres/nails.jpg',category:'nails',alt:'Glossy nail art'},
 {img:'highres/makeup.jpg',category:'nails',alt:'Nail design close up'}
];
function pageHero(title){return `<section class="page-hero"><div class="container"><h1>${title}</h1><div class="breadcrumbs">Home / ${title}</div></div></section>`}
function serviceCards(){return services.slice(0,4).map(s=>`<article class="service-card"><img src="${A+s.img}" alt="${s.title}"><div class="service-card-body"><h3>${s.title}</h3><p>${s.desc}</p></div></article>`).join('')}
function allServiceCards(){return services.map(s=>`<article class="service-card"><img src="${A+s.img}" alt="${s.title}"><div class="service-card-body"><h3>${s.title}</h3><p>${s.desc}</p></div></article>`).join('')}
function home(){return `
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><h1>Enhancing Your<br>Natural Beauty</h1><p>Professional beauty care services in Multan that bring out the best in you.</p><div class="hero-actions"><a class="btn btn-primary" href="#contact">Book Appointment</a><a class="btn btn-outline" href="#services">Explore Services</a></div><div class="feature-row"><div class="feature"><div class="icon">♧</div><strong>Hygienic Environment</strong><small>Clean and safe for you</small></div><div class="feature"><div class="icon">♧</div><strong>Expert Beauticians</strong><small>Trained and experienced</small></div><div class="feature"><div class="icon">♧</div><strong>Premium Products</strong><small>Best quality we use</small></div></div></div><div class="hero-image"><img src="${A}hero.jpg" alt="Beauty client at Moon Beauty Parlor"></div></div></section>
<section class="section"><div class="container"><div class="section-head"><h2>Our Popular Services</h2><p>We offer a wide range of services to make you look and feel your best.</p></div><div class="services-grid">${serviceCards()}</div><div class="center-btn"><a class="btn btn-primary" href="#services">View All Services</a></div></div></section>
<section class="section why"><div class="container"><div class="section-head"><h2>Why Choose Moon Beauty Parlor?</h2><p>We care about your beauty and satisfaction.</p></div><div class="why-grid"><div class="why-item"><div class="icon">♧</div><strong>Trained Professionals</strong><span>Skilled and friendly staff</span></div><div class="why-item"><div class="icon">◉</div><strong>Quality Products</strong><span>We use trusted brands</span></div><div class="why-item"><div class="icon">♡</div><strong>Customer Satisfaction</strong><span>Your happiness is our goal</span></div><div class="why-item"><div class="icon">♧</div><strong>Affordable Prices</strong><span>Best services in budget</span></div></div></div></section>
<section class="cta"><div><h2>Ready to look your best?</h2><p>Book your appointment today and let us pamper you.</p><a class="btn btn-primary" href="#contact">Book Appointment Now</a></div></section>`}
function about(){return pageHero('About Us')+`<section class="section"><div class="container about-grid"><div class="about-image"><img src="${A}interior.jpg" alt="Moon Beauty Parlor interior"></div><div class="about-copy"><h2>Welcome to Moon Beauty Parlor</h2><p>We are a professional beauty salon in Multan committed to providing high quality beauty services. Our goal is to bring out your natural beauty with care and expertise.</p><ul class="checks"><li>Experienced and certified staff</li><li>Hygienic and safe environment</li><li>Modern tools and techniques</li><li>Customer satisfaction is our priority</li></ul><a class="btn btn-primary" href="#contact">Book Appointment</a></div></div></section><section class="stats"><div class="container stats-grid"><div><strong>5+</strong><span>Years Experience</span></div><div><strong>1000+</strong><span>Happy Clients</span></div><div><strong>20+</strong><span>Services</span></div><div><strong>10+</strong><span>Expert Staff</span></div></div></section>`}
function servicesPage(){return pageHero('Our Services')+`<section class="section"><div class="container"><div class="section-head"><p>We offer a variety of beauty services to make you look and feel amazing.</p></div><div class="service-list">${allServiceCards()}</div><div class="center-btn"><a class="btn btn-primary" href="#contact">Book Appointment</a></div></div></section>`}
function galleryPage(){return pageHero('Our Gallery')+`<section class="section"><div class="container"><div class="gallery-filters" role="group" aria-label="Filter gallery"><button class="filter active" type="button" data-filter="all">All</button><button class="filter" type="button" data-filter="bridal">Bridal</button><button class="filter" type="button" data-filter="makeup">Makeup</button><button class="filter" type="button" data-filter="hair">Hair</button><button class="filter" type="button" data-filter="mehndi">Mehndi</button><button class="filter" type="button" data-filter="nails">Nails</button></div><div class="gallery-grid">${gallery.map(g=>`<figure class="gallery-item" data-category="${g.category}"><img loading="lazy" src="${A+g.img}" alt="${g.alt}"></figure>`).join('')}</div></div></section>`}
function blogs(){return pageHero('Beauty Tips & Blogs')+`<section class="section"><div class="container"><div class="section-head"><h2>Simple Beauty Tips</h2><p>Helpful ideas from our team to make your beauty routine easier.</p></div><div class="blog-grid"><article class="blog-card"><img src="${A}skin.jpg" alt="Skin care"><div><h3>How to prepare your skin before an event</h3><p>A few simple steps can help your makeup look fresh and smooth for longer.</p></div></article><article class="blog-card"><img src="${A}hair.jpg" alt="Hair care"><div><h3>Easy hair care habits for busy days</h3><p>Small changes in your routine can help keep your hair healthy and manageable.</p></div></article><article class="blog-card"><img src="${A}bridal.jpg" alt="Bridal makeup"><div><h3>Bridal beauty planning made simple</h3><p>What to book, when to book it, and how to prepare before your big day.</p></div></article></div></div></section>`}
function contact(){return pageHero('Contact Us')+`<section class="section"><div class="container contact-grid"><div class="contact-info"><h2>Get In Touch</h2><p>We would love to hear from you. Feel free to contact us.</p><div class="contact-detail"><strong>☎ Phone</strong>+92 300 1234567</div><div class="contact-detail"><strong>◉ Landline</strong>+92 61 1234567</div><div class="contact-detail"><strong>✉ Email</strong>moonbeautyparlor@gmail.com</div><div class="contact-detail"><strong>📍 Address</strong>123, Model Town, Multan, Pakistan</div><div class="socials"><span>f</span><span>◎</span><span>◉</span></div><div class="map"><iframe loading="lazy" src="https://www.google.com/maps?q=Model%20Town%20Multan%20Pakistan&output=embed" title="Moon Beauty Parlor location"></iframe></div></div><div class="contact-form"><h2>Send Us a Message</h2><form class="form" onsubmit="event.preventDefault(); alert('Thank you! This demo form is ready to connect to your preferred email or WhatsApp workflow.');"><div class="field"><label>Your Name</label><input required type="text"></div><div class="field"><label>Your Email</label><input required type="email"></div><div class="field"><label>Your Phone</label><input type="tel"></div><div class="field"><label>Your Message</label><textarea required></textarea></div><button class="btn btn-primary" type="submit">Send Message</button></form></div></div></section>`}
function initGalleryFilters(){document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.gallery-item').forEach(item=>item.classList.toggle('is-hidden',filter!=='all'&&item.dataset.category!==filter));}));}
function render(){const key=(location.hash||'#home').replace('#','').split('?')[0]||'home';const pages={home,about,services:servicesPage,gallery:galleryPage,blogs,contact};document.getElementById('app').innerHTML=(pages[key]||home)();document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>document.getElementById('mobileNav').classList.remove('open')));initGalleryFilters();window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('mobileNav').classList.toggle('open'));window.addEventListener('hashchange',render);render();
